var classes = [
    {
        "name": "App\\Command\\AdminCreateCommand",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configure",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "execute",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Console\\Command\\Command",
            "Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactoryInterface",
            "App\\Repository\\UserRepository",
            "App\\Entity\\User",
            "Symfony\\Component\\Console\\Input\\InputInterface",
            "Symfony\\Component\\Console\\Output\\OutputInterface"
        ],
        "parents": [
            "Symfony\\Component\\Console\\Command\\Command"
        ],
        "lcom": 2,
        "length": 76,
        "vocabulary": 27,
        "volume": 361.37,
        "difficulty": 2.64,
        "effort": 954.02,
        "level": 0.38,
        "bugs": 0.12,
        "time": 53,
        "intelligentContent": 136.88,
        "number_operators": 10,
        "number_operands": 66,
        "number_operators_unique": 2,
        "number_operands_unique": 25,
        "cloc": 44,
        "loc": 84,
        "lloc": 40,
        "mi": 92.04,
        "mIwoC": 47.01,
        "commentWeight": 45.03,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.16,
        "relativeSystemComplexity": 196.16,
        "totalStructuralComplexity": 588,
        "totalDataComplexity": 0.47,
        "totalSystemComplexity": 588.47,
        "package": "App\\Command\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\DefaultContoller",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Twig\\Environment",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [],
        "lcom": 1,
        "length": 4,
        "vocabulary": 3,
        "volume": 6.34,
        "difficulty": 0.75,
        "effort": 4.75,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 8.45,
        "number_operators": 1,
        "number_operands": 3,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 16,
        "loc": 24,
        "lloc": 8,
        "mi": 122.23,
        "mIwoC": 74.55,
        "commentWeight": 47.68,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "App\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\SecurityController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "login",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\Security\\Http\\Authentication\\AuthenticationUtils",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "lcom": 2,
        "length": 14,
        "vocabulary": 8,
        "volume": 42,
        "difficulty": 1.83,
        "effort": 77,
        "level": 0.55,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 22.91,
        "number_operators": 3,
        "number_operands": 11,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 17,
        "loc": 30,
        "lloc": 13,
        "mi": 110.16,
        "mIwoC": 64.2,
        "commentWeight": 45.96,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.38,
        "relativeSystemComplexity": 9.38,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.75,
        "totalSystemComplexity": 18.75,
        "package": "App\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\TaskCreateController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createTask",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Repository\\TaskRepository",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorageInterface",
            "Twig\\Environment",
            "Symfony\\Component\\Form\\FormFactoryInterface",
            "Symfony\\Component\\Routing\\Generator\\UrlGeneratorInterface",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "Symfony\\Component\\Security\\Core\\Authorization\\AuthorizationCheckerInterface",
            "Symfony\\Component\\HttpFoundation\\Request",
            "App\\Handler\\TaskCreateHandler",
            "App\\Entity\\Task",
            "Symfony\\Component\\HttpFoundation\\RedirectResponse",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [],
        "lcom": 1,
        "length": 49,
        "vocabulary": 17,
        "volume": 200.29,
        "difficulty": 3.96,
        "effort": 793.99,
        "level": 0.25,
        "bugs": 0.07,
        "time": 44,
        "intelligentContent": 50.52,
        "number_operators": 12,
        "number_operands": 37,
        "number_operators_unique": 3,
        "number_operands_unique": 14,
        "cloc": 49,
        "loc": 79,
        "lloc": 30,
        "mi": 98.35,
        "mIwoC": 51.39,
        "commentWeight": 46.96,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.93,
        "relativeSystemComplexity": 36.93,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 1.86,
        "totalSystemComplexity": 73.86,
        "package": "App\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 13,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\TaskDeleteController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "TaskDelete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Repository\\TaskRepository",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorageInterface",
            "Twig\\Environment",
            "Symfony\\Component\\Form\\FormFactoryInterface",
            "Symfony\\Component\\Routing\\Generator\\UrlGeneratorInterface",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "Symfony\\Component\\Security\\Core\\Authorization\\AuthorizationCheckerInterface",
            "App\\Entity\\Task",
            "Symfony\\Component\\HttpFoundation\\RedirectResponse",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [],
        "lcom": 1,
        "length": 46,
        "vocabulary": 19,
        "volume": 195.4,
        "difficulty": 4.67,
        "effort": 911.89,
        "level": 0.21,
        "bugs": 0.07,
        "time": 51,
        "intelligentContent": 41.87,
        "number_operators": 11,
        "number_operands": 35,
        "number_operators_unique": 4,
        "number_operands_unique": 15,
        "cloc": 48,
        "loc": 78,
        "lloc": 30,
        "mi": 98.34,
        "mIwoC": 51.47,
        "commentWeight": 46.87,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.86,
        "relativeSystemComplexity": 36.86,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 1.71,
        "totalSystemComplexity": 73.71,
        "package": "App\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 11,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\TaskDoneController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "taskDone",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Repository\\TaskRepository",
            "Twig\\Environment",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [],
        "lcom": 1,
        "length": 11,
        "vocabulary": 7,
        "volume": 30.88,
        "difficulty": 1.8,
        "effort": 55.59,
        "level": 0.56,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 17.16,
        "number_operators": 2,
        "number_operands": 9,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 17,
        "loc": 26,
        "lloc": 9,
        "mi": 116.11,
        "mIwoC": 68.62,
        "commentWeight": 47.49,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 5,
        "package": "App\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\TaskEditController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "taskEdit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Repository\\TaskRepository",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorageInterface",
            "Twig\\Environment",
            "Symfony\\Component\\Form\\FormFactoryInterface",
            "Symfony\\Component\\Routing\\Generator\\UrlGeneratorInterface",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "Symfony\\Component\\Security\\Core\\Authorization\\AuthorizationCheckerInterface",
            "App\\Entity\\Task",
            "Symfony\\Component\\HttpFoundation\\Request",
            "App\\Handler\\TaskEditHandler",
            "Symfony\\Component\\HttpFoundation\\RedirectResponse",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [],
        "lcom": 1,
        "length": 58,
        "vocabulary": 21,
        "volume": 254.75,
        "difficulty": 5.18,
        "effort": 1318.73,
        "level": 0.19,
        "bugs": 0.08,
        "time": 73,
        "intelligentContent": 49.21,
        "number_operators": 14,
        "number_operands": 44,
        "number_operators_unique": 4,
        "number_operands_unique": 17,
        "cloc": 52,
        "loc": 84,
        "lloc": 32,
        "mi": 96.85,
        "mIwoC": 49.92,
        "commentWeight": 46.94,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 50,
        "totalStructuralComplexity": 98,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 100,
        "package": "App\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 13,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\TaskListController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "tasksList",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Repository\\TaskRepository",
            "Twig\\Environment",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 2,
        "effort": 51.7,
        "level": 0.5,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 12.92,
        "number_operators": 2,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 17,
        "loc": 26,
        "lloc": 9,
        "mi": 116.65,
        "mIwoC": 69.16,
        "commentWeight": 47.49,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 5,
        "package": "App\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\TaskSwitchController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "switchTask",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Entity\\Task",
            "App\\Repository\\TaskRepository",
            "Symfony\\Component\\Routing\\Generator\\UrlGeneratorInterface",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "Symfony\\Component\\HttpFoundation\\RedirectResponse",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [],
        "lcom": 1,
        "length": 17,
        "vocabulary": 10,
        "volume": 56.47,
        "difficulty": 3,
        "effort": 169.42,
        "level": 0.33,
        "bugs": 0.02,
        "time": 9,
        "intelligentContent": 18.82,
        "number_operators": 3,
        "number_operands": 14,
        "number_operators_unique": 3,
        "number_operands_unique": 7,
        "cloc": 17,
        "loc": 30,
        "lloc": 13,
        "mi": 109.13,
        "mIwoC": 63.17,
        "commentWeight": 45.96,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.63,
        "relativeSystemComplexity": 49.63,
        "totalStructuralComplexity": 49,
        "totalDataComplexity": 0.63,
        "totalSystemComplexity": 49.63,
        "package": "App\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\UserCreateController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "userCreate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Twig\\Environment",
            "Symfony\\Component\\Form\\FormFactoryInterface",
            "Symfony\\Component\\Routing\\Generator\\UrlGeneratorInterface",
            "App\\Repository\\UserRepository",
            "Symfony\\Component\\HttpFoundation\\Request",
            "App\\Handler\\UserCreateHandler",
            "App\\Entity\\User",
            "Symfony\\Component\\HttpFoundation\\RedirectResponse",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [],
        "lcom": 1,
        "length": 37,
        "vocabulary": 14,
        "volume": 140.87,
        "difficulty": 3.82,
        "effort": 537.88,
        "level": 0.26,
        "bugs": 0.05,
        "time": 30,
        "intelligentContent": 36.9,
        "number_operators": 9,
        "number_operands": 28,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 37,
        "loc": 61,
        "lloc": 24,
        "mi": 101.3,
        "mIwoC": 54.58,
        "commentWeight": 46.72,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.71,
        "relativeSystemComplexity": 36.71,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 1.43,
        "totalSystemComplexity": 73.43,
        "package": "App\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 10,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\UserDeleteController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Twig\\Environment",
            "Symfony\\Component\\Routing\\Generator\\UrlGeneratorInterface",
            "App\\Repository\\UserRepository",
            "App\\Entity\\User",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorageInterface",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "Symfony\\Component\\HttpFoundation\\RedirectResponse",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [],
        "lcom": 1,
        "length": 27,
        "vocabulary": 14,
        "volume": 102.8,
        "difficulty": 4.2,
        "effort": 431.75,
        "level": 0.24,
        "bugs": 0.03,
        "time": 24,
        "intelligentContent": 24.48,
        "number_operators": 6,
        "number_operands": 21,
        "number_operators_unique": 4,
        "number_operands_unique": 10,
        "cloc": 33,
        "loc": 54,
        "lloc": 21,
        "mi": 103.6,
        "mIwoC": 56.8,
        "commentWeight": 46.8,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.57,
        "relativeSystemComplexity": 36.57,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 1.14,
        "totalSystemComplexity": 73.14,
        "package": "App\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\UserEditController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "userEdit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Twig\\Environment",
            "Symfony\\Component\\Form\\FormFactoryInterface",
            "Symfony\\Component\\Routing\\Generator\\UrlGeneratorInterface",
            "App\\Repository\\UserRepository",
            "App\\Entity\\User",
            "Symfony\\Component\\HttpFoundation\\Request",
            "App\\Handler\\UserEditHandler",
            "Symfony\\Component\\HttpFoundation\\RedirectResponse",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [],
        "lcom": 1,
        "length": 37,
        "vocabulary": 14,
        "volume": 140.87,
        "difficulty": 3.95,
        "effort": 557.09,
        "level": 0.25,
        "bugs": 0.05,
        "time": 31,
        "intelligentContent": 35.62,
        "number_operators": 8,
        "number_operands": 29,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 38,
        "loc": 61,
        "lloc": 23,
        "mi": 101.98,
        "mIwoC": 54.98,
        "commentWeight": 47,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.79,
        "relativeSystemComplexity": 36.79,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 1.57,
        "totalSystemComplexity": 73.57,
        "package": "App\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 10,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\UserEditPasswordController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "userEditPassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Twig\\Environment",
            "Symfony\\Component\\Form\\FormFactoryInterface",
            "Symfony\\Component\\Routing\\Generator\\UrlGeneratorInterface",
            "App\\Repository\\UserRepository",
            "App\\Entity\\User",
            "Symfony\\Component\\HttpFoundation\\Request",
            "App\\Handler\\UserEditPasswordHandler",
            "Symfony\\Component\\HttpFoundation\\RedirectResponse",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [],
        "lcom": 1,
        "length": 38,
        "vocabulary": 14,
        "volume": 144.68,
        "difficulty": 4.09,
        "effort": 591.87,
        "level": 0.24,
        "bugs": 0.05,
        "time": 33,
        "intelligentContent": 35.37,
        "number_operators": 8,
        "number_operands": 30,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 40,
        "loc": 63,
        "lloc": 23,
        "mi": 102.1,
        "mIwoC": 54.9,
        "commentWeight": 47.2,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.79,
        "relativeSystemComplexity": 36.79,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 1.57,
        "totalSystemComplexity": 73.57,
        "package": "App\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 10,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\UserListController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "listUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Repository\\UserRepository",
            "Twig\\Environment",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 7,
        "volume": 28.07,
        "difficulty": 1.6,
        "effort": 44.92,
        "level": 0.63,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 17.55,
        "number_operators": 2,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 17,
        "loc": 26,
        "lloc": 9,
        "mi": 116.4,
        "mIwoC": 68.91,
        "commentWeight": 47.49,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 5,
        "package": "App\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\DataFixtures\\TaskFixtures",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "load",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDependencies",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture",
            "Doctrine\\Common\\DataFixtures\\DependentFixtureInterface",
            "Doctrine\\Persistence\\ObjectManager",
            "Faker\\Factory",
            "App\\Entity\\Task",
            "DateTimeImmutable"
        ],
        "parents": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture"
        ],
        "lcom": 2,
        "length": 37,
        "vocabulary": 16,
        "volume": 148,
        "difficulty": 5.91,
        "effort": 874.55,
        "level": 0.17,
        "bugs": 0.05,
        "time": 49,
        "intelligentContent": 25.05,
        "number_operators": 11,
        "number_operands": 26,
        "number_operators_unique": 5,
        "number_operands_unique": 11,
        "cloc": 11,
        "loc": 34,
        "lloc": 23,
        "mi": 93.27,
        "mIwoC": 54.7,
        "commentWeight": 38.57,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.15,
        "relativeSystemComplexity": 81.15,
        "totalStructuralComplexity": 162,
        "totalDataComplexity": 0.3,
        "totalSystemComplexity": 162.3,
        "package": "App\\DataFixtures\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\DataFixtures\\UserFixtures",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "load",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture",
            "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface",
            "Doctrine\\Persistence\\ObjectManager",
            "App\\Entity\\User"
        ],
        "parents": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture"
        ],
        "lcom": 1,
        "length": 41,
        "vocabulary": 17,
        "volume": 167.59,
        "difficulty": 4.77,
        "effort": 799.26,
        "level": 0.21,
        "bugs": 0.06,
        "time": 44,
        "intelligentContent": 35.14,
        "number_operators": 10,
        "number_operands": 31,
        "number_operators_unique": 4,
        "number_operands_unique": 13,
        "cloc": 16,
        "loc": 39,
        "lloc": 23,
        "mi": 96.32,
        "mIwoC": 54.45,
        "commentWeight": 41.86,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.11,
        "relativeSystemComplexity": 64.11,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 0.22,
        "totalSystemComplexity": 128.22,
        "package": "App\\DataFixtures\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Entity\\Task",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCreatedAt",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setCreatedAt",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTitle",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setTitle",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getContent",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setContent",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isDone",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setIsDone",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "switch",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDateIsDone",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setDateIsDone",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUser",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUser",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 14,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 6,
        "nbMethodsSetters": 7,
        "wmc": 14,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "DateTimeImmutable",
            "DateTimeImmutable",
            "DateTimeImmutable",
            "App\\Entity\\User",
            "App\\Entity\\User"
        ],
        "parents": [],
        "lcom": 1,
        "length": 44,
        "vocabulary": 10,
        "volume": 146.16,
        "difficulty": 3.63,
        "effort": 529.85,
        "level": 0.28,
        "bugs": 0.05,
        "time": 29,
        "intelligentContent": 40.32,
        "number_operators": 15,
        "number_operands": 29,
        "number_operators_unique": 2,
        "number_operands_unique": 8,
        "cloc": 91,
        "loc": 159,
        "lloc": 68,
        "mi": 90.81,
        "mIwoC": 44.73,
        "commentWeight": 46.08,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 6.5,
        "relativeSystemComplexity": 6.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 91,
        "totalSystemComplexity": 91,
        "package": "App\\Entity\\",
        "pageRank": 0.26,
        "afferentCoupling": 9,
        "efferentCoupling": 2,
        "instability": 0.18,
        "violations": {}
    },
    {
        "name": "App\\Entity\\Traits\\Idtrait",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0.5,
        "effort": 1,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 1,
        "number_operands": 1,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 15,
        "loc": 24,
        "lloc": 9,
        "mi": 123.98,
        "mIwoC": 76.94,
        "commentWeight": 47.04,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\Entity\\Traits\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Entity\\User",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUsername",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUsername",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPassword",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPassword",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEmail",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setEmail",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCreatedAt",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setCreatedAt",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTask",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setTask",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRoles",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setRoles",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSalt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "eraseCredentials",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 15,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 5,
        "nbMethodsSetters": 6,
        "wmc": 15,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Security\\Core\\User\\UserInterface",
            "DateTimeImmutable",
            "DateTimeImmutable",
            "DateTimeImmutable",
            "App\\Entity\\Task",
            "App\\Entity\\Task"
        ],
        "parents": [],
        "lcom": 3,
        "length": 38,
        "vocabulary": 9,
        "volume": 120.46,
        "difficulty": 3.57,
        "effort": 430.2,
        "level": 0.28,
        "bugs": 0.04,
        "time": 24,
        "intelligentContent": 33.73,
        "number_operators": 13,
        "number_operands": 25,
        "number_operators_unique": 2,
        "number_operands_unique": 7,
        "cloc": 103,
        "loc": 172,
        "lloc": 69,
        "mi": 91.76,
        "mIwoC": 45.18,
        "commentWeight": 46.58,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 6.4,
        "relativeSystemComplexity": 6.4,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 96,
        "totalSystemComplexity": 96,
        "package": "App\\Entity\\",
        "pageRank": 0.28,
        "afferentCoupling": 10,
        "efferentCoupling": 3,
        "instability": 0.23,
        "violations": {}
    },
    {
        "name": "App\\Form\\TaskType",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 1,
        "length": 9,
        "vocabulary": 7,
        "volume": 25.27,
        "difficulty": 0,
        "effort": 0,
        "level": 1.56,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 39.3,
        "number_operators": 0,
        "number_operands": 9,
        "number_operators_unique": 0,
        "number_operands_unique": 7,
        "cloc": 9,
        "loc": 17,
        "lloc": 8,
        "mi": 115.51,
        "mIwoC": 70.34,
        "commentWeight": 45.16,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "App\\Form\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Form\\UserCreateType",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 1,
        "length": 18,
        "vocabulary": 16,
        "volume": 72,
        "difficulty": 0,
        "effort": 0,
        "level": 1.78,
        "bugs": 0.02,
        "time": 0,
        "intelligentContent": 128,
        "number_operators": 0,
        "number_operands": 18,
        "number_operators_unique": 0,
        "number_operands_unique": 16,
        "cloc": 10,
        "loc": 18,
        "lloc": 8,
        "mi": 112.89,
        "mIwoC": 67.16,
        "commentWeight": 45.73,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "App\\Form\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Form\\UserEditPasswordType",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 1,
        "length": 12,
        "vocabulary": 10,
        "volume": 39.86,
        "difficulty": 0,
        "effort": 0,
        "level": 1.67,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 66.44,
        "number_operators": 0,
        "number_operands": 12,
        "number_operators_unique": 0,
        "number_operands_unique": 10,
        "cloc": 9,
        "loc": 17,
        "lloc": 8,
        "mi": 114.12,
        "mIwoC": 68.96,
        "commentWeight": 45.16,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "App\\Form\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Form\\UserEditType",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 1,
        "length": 27,
        "vocabulary": 22,
        "volume": 120.4,
        "difficulty": 0,
        "effort": 0,
        "level": 1.63,
        "bugs": 0.04,
        "time": 0,
        "intelligentContent": 196.21,
        "number_operators": 0,
        "number_operands": 27,
        "number_operators_unique": 0,
        "number_operands_unique": 22,
        "cloc": 10,
        "loc": 18,
        "lloc": 8,
        "mi": 111.33,
        "mIwoC": 65.6,
        "commentWeight": 45.73,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "App\\Form\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Form\\UserType",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 1,
        "length": 27,
        "vocabulary": 22,
        "volume": 120.4,
        "difficulty": 0,
        "effort": 0,
        "level": 1.63,
        "bugs": 0.04,
        "time": 0,
        "intelligentContent": 196.21,
        "number_operators": 0,
        "number_operands": 27,
        "number_operators_unique": 0,
        "number_operands_unique": 22,
        "cloc": 10,
        "loc": 18,
        "lloc": 8,
        "mi": 111.33,
        "mIwoC": 65.6,
        "commentWeight": 45.73,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "App\\Form\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Handler\\TaskCreateHandler",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Repository\\TaskRepository",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorageInterface",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "Symfony\\Component\\Form\\FormInterface",
            "App\\Entity\\Task"
        ],
        "parents": [],
        "lcom": 1,
        "length": 27,
        "vocabulary": 12,
        "volume": 96.79,
        "difficulty": 5,
        "effort": 483.97,
        "level": 0.2,
        "bugs": 0.03,
        "time": 27,
        "intelligentContent": 19.36,
        "number_operators": 7,
        "number_operands": 20,
        "number_operators_unique": 4,
        "number_operands_unique": 8,
        "cloc": 27,
        "loc": 50,
        "lloc": 23,
        "mi": 101.39,
        "mIwoC": 55.99,
        "commentWeight": 45.4,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 64.5,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 129,
        "package": "App\\Handler\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "App\\Handler\\TaskEditHandler",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Repository\\TaskRepository",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "Symfony\\Component\\Form\\FormInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 19,
        "vocabulary": 10,
        "volume": 63.12,
        "difficulty": 4.33,
        "effort": 273.51,
        "level": 0.23,
        "bugs": 0.02,
        "time": 15,
        "intelligentContent": 14.57,
        "number_operators": 6,
        "number_operands": 13,
        "number_operators_unique": 4,
        "number_operands_unique": 6,
        "cloc": 25,
        "loc": 45,
        "lloc": 20,
        "mi": 104.34,
        "mIwoC": 58.61,
        "commentWeight": 45.73,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.58,
        "relativeSystemComplexity": 25.58,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 1.17,
        "totalSystemComplexity": 51.17,
        "package": "App\\Handler\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "App\\Handler\\UserCreateHandler",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Repository\\UserRepository",
            "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "Symfony\\Component\\Form\\FormInterface",
            "App\\Entity\\User"
        ],
        "parents": [],
        "lcom": 1,
        "length": 32,
        "vocabulary": 13,
        "volume": 118.41,
        "difficulty": 5.33,
        "effort": 631.54,
        "level": 0.19,
        "bugs": 0.04,
        "time": 35,
        "intelligentContent": 22.2,
        "number_operators": 8,
        "number_operands": 24,
        "number_operators_unique": 4,
        "number_operands_unique": 9,
        "cloc": 27,
        "loc": 51,
        "lloc": 24,
        "mi": 100.13,
        "mIwoC": 54.97,
        "commentWeight": 45.16,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 64.5,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 129,
        "package": "App\\FormHandler\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "App\\Handler\\UserEditHandler",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Repository\\UserRepository",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "Symfony\\Component\\Form\\FormInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 19,
        "vocabulary": 10,
        "volume": 63.12,
        "difficulty": 4.33,
        "effort": 273.51,
        "level": 0.23,
        "bugs": 0.02,
        "time": 15,
        "intelligentContent": 14.57,
        "number_operators": 6,
        "number_operands": 13,
        "number_operators_unique": 4,
        "number_operands_unique": 6,
        "cloc": 25,
        "loc": 45,
        "lloc": 20,
        "mi": 104.34,
        "mIwoC": 58.61,
        "commentWeight": 45.73,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.58,
        "relativeSystemComplexity": 25.58,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 1.17,
        "totalSystemComplexity": 51.17,
        "package": "App\\FormHandler\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "App\\Handler\\UserEditPasswordHandler",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Repository\\UserRepository",
            "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "Symfony\\Component\\Form\\FormInterface",
            "App\\Entity\\User"
        ],
        "parents": [],
        "lcom": 1,
        "length": 31,
        "vocabulary": 13,
        "volume": 114.71,
        "difficulty": 5.11,
        "effort": 586.31,
        "level": 0.2,
        "bugs": 0.04,
        "time": 33,
        "intelligentContent": 22.44,
        "number_operators": 8,
        "number_operands": 23,
        "number_operators_unique": 4,
        "number_operands_unique": 9,
        "cloc": 30,
        "loc": 54,
        "lloc": 24,
        "mi": 100.8,
        "mIwoC": 55.07,
        "commentWeight": 45.73,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 64.5,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 129,
        "package": "App\\Handler\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "App\\Listener\\TaskListener",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "postPersist",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "postUpdate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "postRemove",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Entity\\Task",
            "Doctrine\\ORM\\Event\\LifecycleEventArgs",
            "App\\Entity\\Task",
            "Doctrine\\ORM\\Event\\LifecycleEventArgs",
            "App\\Entity\\Task",
            "Doctrine\\ORM\\Event\\LifecycleEventArgs"
        ],
        "parents": [],
        "lcom": 1,
        "length": 19,
        "vocabulary": 7,
        "volume": 53.34,
        "difficulty": 1.5,
        "effort": 80.01,
        "level": 0.67,
        "bugs": 0.02,
        "time": 4,
        "intelligentContent": 35.56,
        "number_operators": 1,
        "number_operands": 18,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 25,
        "loc": 46,
        "lloc": 21,
        "mi": 104.4,
        "mIwoC": 58.93,
        "commentWeight": 45.48,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.88,
        "relativeSystemComplexity": 1.88,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 3.5,
        "totalSystemComplexity": 7.5,
        "package": "App\\Listener\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "DoctrineMigrations\\Version20200423093551",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "getDescription",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Doctrine\\Migrations\\AbstractMigration",
            "Doctrine\\DBAL\\Schema\\Schema",
            "Doctrine\\DBAL\\Schema\\Schema"
        ],
        "parents": [
            "Doctrine\\Migrations\\AbstractMigration"
        ],
        "lcom": 2,
        "length": 32,
        "vocabulary": 11,
        "volume": 110.7,
        "difficulty": 3,
        "effort": 332.11,
        "level": 0.33,
        "bugs": 0.04,
        "time": 18,
        "intelligentContent": 36.9,
        "number_operators": 5,
        "number_operands": 27,
        "number_operators_unique": 2,
        "number_operands_unique": 9,
        "cloc": 5,
        "loc": 27,
        "lloc": 22,
        "mi": 87.19,
        "mIwoC": 56.27,
        "commentWeight": 30.92,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 16.33,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 49,
        "package": "DoctrineMigrations\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Repository\\TaskRepository",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "listTask",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "save",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository",
            "Doctrine\\Persistence\\ManagerRegistry"
        ],
        "parents": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository"
        ],
        "lcom": 3,
        "length": 19,
        "vocabulary": 10,
        "volume": 63.12,
        "difficulty": 1,
        "effort": 63.12,
        "level": 1,
        "bugs": 0.02,
        "time": 4,
        "intelligentContent": 63.12,
        "number_operators": 1,
        "number_operands": 18,
        "number_operators_unique": 1,
        "number_operands_unique": 9,
        "cloc": 25,
        "loc": 51,
        "lloc": 26,
        "mi": 100.6,
        "mIwoC": 56.39,
        "commentWeight": 44.21,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0.12,
        "relativeSystemComplexity": 144.12,
        "totalStructuralComplexity": 720,
        "totalDataComplexity": 0.62,
        "totalSystemComplexity": 720.62,
        "package": "App\\Repository\\",
        "pageRank": 0.05,
        "afferentCoupling": 8,
        "efferentCoupling": 2,
        "instability": 0.2,
        "violations": {}
    },
    {
        "name": "App\\Repository\\UserRepository",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "userSave",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "userUpdate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "userDelete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository",
            "Doctrine\\Persistence\\ManagerRegistry"
        ],
        "parents": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository"
        ],
        "lcom": 2,
        "length": 11,
        "vocabulary": 3,
        "volume": 17.43,
        "difficulty": 0,
        "effort": 0,
        "level": 0.55,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 0,
        "number_operands": 11,
        "number_operators_unique": 0,
        "number_operands_unique": 3,
        "cloc": 22,
        "loc": 44,
        "lloc": 22,
        "mi": 106.35,
        "mIwoC": 61.89,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.15,
        "relativeSystemComplexity": 16.15,
        "totalStructuralComplexity": 64,
        "totalDataComplexity": 0.6,
        "totalSystemComplexity": 64.6,
        "package": "App\\Repository\\",
        "pageRank": 0.05,
        "afferentCoupling": 9,
        "efferentCoupling": 2,
        "instability": 0.18,
        "violations": {}
    },
    {
        "name": "App\\Security\\LoginFormAuthenticator",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLoginUrl",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "supports",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCredentials",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "checkCredentials",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onAuthenticationSuccess",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Component\\Security\\Guard\\Authenticator\\AbstractFormLoginAuthenticator",
            "Doctrine\\ORM\\EntityManagerInterface",
            "Symfony\\Component\\Routing\\Generator\\UrlGeneratorInterface",
            "Symfony\\Component\\Security\\Csrf\\CsrfTokenManagerInterface",
            "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Security\\Core\\User\\UserProviderInterface",
            "Symfony\\Component\\Security\\Csrf\\CsrfToken",
            "Symfony\\Component\\Security\\Core\\Exception\\InvalidCsrfTokenException",
            "Symfony\\Component\\Security\\Core\\Exception\\CustomUserMessageAuthenticationException",
            "Symfony\\Component\\Security\\Core\\User\\UserInterface",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface",
            "Symfony\\Component\\HttpFoundation\\RedirectResponse",
            "Symfony\\Component\\HttpFoundation\\RedirectResponse"
        ],
        "parents": [
            "Symfony\\Component\\Security\\Guard\\Authenticator\\AbstractFormLoginAuthenticator"
        ],
        "lcom": 3,
        "length": 87,
        "vocabulary": 29,
        "volume": 422.64,
        "difficulty": 6.98,
        "effort": 2949.71,
        "level": 0.14,
        "bugs": 0.14,
        "time": 164,
        "intelligentContent": 60.56,
        "number_operators": 20,
        "number_operands": 67,
        "number_operators_unique": 5,
        "number_operands_unique": 24,
        "cloc": 59,
        "loc": 112,
        "lloc": 53,
        "mi": 88.43,
        "mIwoC": 43.33,
        "commentWeight": 45.1,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.81,
        "relativeSystemComplexity": 100.81,
        "totalStructuralComplexity": 700,
        "totalDataComplexity": 5.64,
        "totalSystemComplexity": 705.64,
        "package": "App\\Security\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 13,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Voter\\TaskVoter",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "supports",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "voteOnAttribute",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "canEdit",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "canDelete",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 4,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 8,
        "ccnMethodMax": 4,
        "externals": [
            "Symfony\\Component\\Security\\Core\\Authorization\\Voter\\Voter",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface",
            "LogicException",
            "App\\Entity\\Task",
            "App\\Entity\\User",
            "App\\Entity\\Task",
            "App\\Entity\\User"
        ],
        "parents": [
            "Symfony\\Component\\Security\\Core\\Authorization\\Voter\\Voter"
        ],
        "lcom": 2,
        "length": 55,
        "vocabulary": 17,
        "volume": 224.81,
        "difficulty": 11.55,
        "effort": 2596.56,
        "level": 0.09,
        "bugs": 0.07,
        "time": 144,
        "intelligentContent": 19.46,
        "number_operators": 22,
        "number_operands": 33,
        "number_operators_unique": 7,
        "number_operands_unique": 10,
        "cloc": 36,
        "loc": 78,
        "lloc": 42,
        "mi": 90.48,
        "mIwoC": 47.05,
        "commentWeight": 43.43,
        "kanDefect": 0.65,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 2.25,
        "relativeSystemComplexity": 18.25,
        "totalStructuralComplexity": 64,
        "totalDataComplexity": 9,
        "totalSystemComplexity": 73,
        "package": "App\\Voter\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    }
]